GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Ordering protein"
}

###

DELETE http://localhost:3001/todo/delete/6496ca608686bd1895332dd7

###

PUT http://localhost:3001/todo/complete/6496ca5e8686bd1895332dd4
